/**
 * @class service.{{table.Name}}
 * @author generated by Find
 */
class Service extends require('./base.service') {

}

module.exports = (Sequelize, { sequelize }) => {
    const model = require('../models/{{table.Name}}')(Sequelize, sequelize)
    return new Service(model)
}