/**
 * @class {{table.Name}}
 * @author generated by Find
 */
module.exports = (Sequelize, sequelize) => {
    <% 
    function type(Type) {
        if (Type === 'text') {
            return 'Sequelize.TEXT'
        } else if (Type === 'timestamp' || Type === 'datetime') {
            return 'Sequelize.DATE'
        } else if (Type === 'date') {
            return 'Sequelize.DATEONLY'
        } else if (Type === 'double') {
            return 'Sequelize.DOUBLE'
        } else if (Type === 'float') {
            return 'Sequelize.FLOAT'
        } else if (Type === 'decimal') {
            return 'Sequelize.DECIMAL'
        } else if (Type.startsWith('year(')) {
            return 'Sequelize.CHAR('+ Type.substring(Type.indexOf('(') + 1,Type.lastIndexOf(')')) + ')'
        } else if (Type.startsWith('datetime(') || Type.startsWith('timestamp(')) {
            return 'Sequelize.DATE('+ Type.substring(Type.indexOf('(') + 1,Type.lastIndexOf(')')) + ')'
        } else if (Type.startsWith('varchar(')) {
            return 'Sequelize.STRING(' + Type.substring(Type.indexOf('(') + 1,Type.lastIndexOf(')')) + ')'
        } else if (Type.startsWith('int(')) {
            return 'Sequelize.INTEGER'
        } else if (Type.startsWith('tinyint(1)')) {
            return 'Sequelize.BOOLEAN'
        } else {
            return 'Sequelize.UN'
        }
    }
    function defaultValue(column) {
        if (column.Default) {
            var seq_type = type(column.Type.toLowerCase())
            if (seq_type.startsWith('Sequelize.DATE')) {
                return column.Default === 'CURRENT_TIMESTAMP' ? 'Sequelize.NOW' : column.Default
            }
            return column.Default
        } else {
            return 'false'
        }
    }
    %>
    return sequelize.define('{{table.Name}}', {
        <% for(var i = 0; i < columns.length; i++){ %><% var column = columns[i] %>
        <%=column.Field %>: {
            type: <%=type(column.Type.toLowerCase()) %>,
            allowNull: <%= column.Null === 'NO' ? 'false' : 'true' %>,
            defaultValue: <%=defaultValue(column) %>,
            comment: '<%=column.Comment %>'
        },
        <% } %>
    }, { freezeTableName: true, timestamps: false, comment: '{{table.Comment}}' })
}